<script lang="ts">
    import { goto } from '$app/navigation';
    import { getGame, initializeGameDatabase } from '../firebase/firebase';
	import GraphScore from './GraphScore.svelte';


    let gameCode = $state('');
    let playerName = $state('');
    let error = $state('');

    async function handleSubmit(event: Event) {
        event.preventDefault();

        // Validate inputs
        if (!gameCode.trim()) {
            error = 'Game Code is required';
            return;
        }
        if (!playerName.trim()) {
            error = 'Player Name is required';
            return;
        }

        try {
            // Initialize the game database structure if it doesn't exist
            const game = await getGame(gameCode);
            if (!game) {
                await initializeGameDatabase(gameCode);
            }
            // Save game details in local storage
            localStorage.setItem('gameCode', gameCode);
            localStorage.setItem('playerName', playerName);

            document.cookie = `gameCode=${gameCode}; path=/; SameSite=Strict`;
            document.cookie = `playerName=${playerName}; path=/; SameSite=Strict`;

            // Redirect to the main game page
            await goto(`/play/${gameCode}`);
        } catch (err) {
            console.error('Error entering game:', err);
            error = 'Failed to enter game. Please try again.';
        }
    }
</script>

<div class="min-h-screen flex flex-col items-center bg-gray-100 py-8">
    <div class="bg-white p-6 rounded-lg shadow-md max-w-3xl text-center mb-8">
        <h1 class="text-3xl font-bold mb-4">Welcome to "Who Knows Who"</h1>
        <p class="text-gray-700 mb-4">
            "Who Knows Who" is a fun, interactive game where players guess answers to questions about their friends, generated by AI using Gemini. Each round, a player is randomly selected and you have to guess their answer to the question. Are you ready to test your knowledge? Have fun!
        </p>
    </div>

    <GraphScore gameCode="exampleGame" />


    <div class="bg-white p-8 rounded-lg shadow-md w-96">
        <h2 class="text-2xl font-bold mb-6 text-center">Enter Game</h2>

        {#if error}
            <div class="bg-red-100 text-red-700 p-3 rounded mb-4">
                {error}
            </div>
        {/if}

        <form onsubmit={handleSubmit}>
            <div class="mb-4">
                <label for="gameCode" class="block text-gray-700 font-bold mb-2">
                    Game Code
                </label>
                <input 
                    type="text" 
                    id="gameCode" 
                    bind:value={gameCode}
                    class="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter Game Code"
                    required
                />
            </div>

            <div class="mb-6">
                <label for="playerName" class="block text-gray-700 font-bold mb-2">
                    Player Name
                </label>
                <input 
                    type="text" 
                    id="playerName" 
                    bind:value={playerName}
                    class="w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter Your Name"
                    required
                />
            </div>

            <button 
                type="submit" 
                class="w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600 transition duration-300"
            >
                Enter Game
            </button>
        </form>
    </div>
</div>
